version: "3.8"
services:
  quiz-lite-postgres:
    image: postgres
    container_name: quiz-lite-postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=quiz_lite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata: 
      

